services:
  - type: web
    name: church-project
    env: python
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn church_platform.wsgi:application
    runtime: python-3.11.9